// These tests use Node built-ins only. They run without MongoDB or npm dependencies.
import test from 'node:test';
import assert from 'node:assert/strict';
import {AppError,text,integer,money,email,password,id,choice,date,safeUrl,normalize,pageParams,paginate,encrypt,decrypt,token,hash,sign,equal,csvCell,same} from '../src/core.js';
const bad=fn=>assert.throws(fn,e=>e instanceof AppError&&e.status===400);
const key='a'.repeat(64);
test('text trims normal fields and enforces boundaries',()=>{assert.equal(text('  Salaam  ','Name',2,10),'Salaam');bad(()=>text('x','Name',2,10));bad(()=>text('x'.repeat(11),'Name',2,10));});
test('text rejects Mongo operator objects and control characters',()=>{bad(()=>text({$ne:null},'Name'));bad(()=>text('bad\u0000input','Name'));});
test('text permits meaningful multilingual paragraphs',()=>{assert.equal(text('السلام علیکم\nHello','Message',1,100),'السلام علیکم\nHello');});
test('integer accepts numeric form values and rejects fractions/ranges',()=>{assert.equal(integer('114','Surah',1,114),114);for(const n of [0,115,1.5,'NaN',Infinity])bad(()=>integer(n,'Surah',1,114));});
test('integer rejects coercible nonnumeric input types',()=>{for(const x of [true,false,null,[],{},''])bad(()=>integer(x,'Count',0,100));});
test('money preserves nonnegative two-decimal values and rejects invalid values',()=>{assert.equal(money('1234.567'),1234.57);assert.equal(money(0),0);for(const x of [-1,10000001,Infinity,{},[],true,null,''])bad(()=>money(x));});
test('email supports plus addressing and long domains',()=>{assert.equal(email(' Student+Quran@Example.Education '),'student+quran@example.education');bad(()=>email('not-an-email'));bad(()=>email({$regex:'.*'}));});
test('password preserves whitespace rather than silently changing a secret',()=>{assert.equal(password('  VeryLongSecret  '),'  VeryLongSecret  ');bad(()=>password('short'));});
test('password enforces bcrypt UTF-8 byte ceiling',()=>{assert.equal(password('a'.repeat(72)).length,72);bad(()=>password('a'.repeat(73)));bad(()=>password('🙂'.repeat(19)));assert.equal(password('🙂'.repeat(18)).length,36);});
test('ObjectId validation rejects arbitrary Mongo operators and malformed IDs',()=>{assert.equal(id('f'.repeat(24)),'f'.repeat(24));for(const x of ['123',{$ne:null},'g'.repeat(24),null])bad(()=>id(x));});
test('choice is an explicit allowlist',()=>{assert.equal(choice('student',['student','ulma']),'student');bad(()=>choice('admin',['student','ulma']));});
test('date validates invalid values',()=>{assert.equal(date('2026-10-02').toISOString(),'2026-10-02T00:00:00.000Z');bad(()=>date('invalid-date'));bad(()=>date(null));});
test('external links require HTTPS and forbid embedded credentials',()=>{assert.equal(safeUrl('https://example.org/lesson'),'https://example.org/lesson');assert.equal(safeUrl(''),'');for(const x of ['http://example.org','javascript:alert(1)','data:text/html,test','https://user:secret@example.org','not a URL'])bad(()=>safeUrl(x));});
test('Arabic search normalization handles diacritics and alef variants',()=>{assert.equal(normalize('ٱلْحَمْدُ'),'الحمد');assert.equal(normalize('إِيمَان'),'ايمان');});
test('search normalization handles Latin accents and Urdu character variants',()=>{assert.equal(normalize('  CAFÉ  '),'cafe');assert.equal(normalize('کی'),'كي');});
test('pagination reports empty state without fabricated results',()=>{assert.deepEqual(paginate([],{page:'1'}),{items:[],total:0,page:1,pages:1});});
test('pagination slices and validates upper limits',()=>{assert.deepEqual(paginate([1,2,3,4,5],{page:2,limit:2}),{items:[3,4],total:5,page:2,pages:3});bad(()=>pageParams({limit:101}));bad(()=>pageParams({page:0}));});
test('secure session token shape and uniqueness',()=>{const a=token(),b=token();assert.match(a,/^[a-f\d]{64}$/);assert.notEqual(a,b);});
test('session token hashing is deterministic and does not store the raw token',()=>{const a=token();assert.equal(hash(a),hash(a));assert.notEqual(hash(a),a);assert.equal(hash(a).length,64);});
test('CSRF HMAC depends on the configured secret',()=>{assert.equal(sign('nonce','secret'),sign('nonce','secret'));assert.notEqual(sign('nonce','other'),sign('nonce','secret'));});
test('constant-time comparator rejects wrong values and types',()=>{assert.equal(equal('abc','abc'),true);for(const b of ['abd','ab',null,{},undefined])assert.equal(equal('abc',b),false);});
test('AES-GCM round trip supports Arabic and Unicode messages',()=>{const s='السلام علیکم\nA private message 🌙';const e=encrypt(s,key);assert.match(e,/^enc:v1:/);assert.ok(!e.includes('private'));assert.equal(decrypt(e,key),s);});
test('AES-GCM uses a fresh IV for identical plaintext',()=>{assert.notEqual(encrypt('same',key),encrypt('same',key));});
test('AES-GCM rejects the wrong key',()=>{assert.throws(()=>decrypt(encrypt('secret',key),'b'.repeat(64)));});
test('AES-GCM rejects ciphertext tampering',()=>{const parts=encrypt('private message',key).split(':');const bytes=Buffer.from(parts[4],'base64');bytes[0]^=1;parts[4]=bytes.toString('base64');assert.throws(()=>decrypt(parts.join(':'),key));});
test('AES-GCM rejects tampered authentication tag',()=>{const parts=encrypt('secret',key).split(':');parts[3]=Buffer.alloc(16).toString('base64');assert.throws(()=>decrypt(parts.join(':'),key));});
test('invalid encryption key fails rather than storing plaintext',()=>{assert.throws(()=>encrypt('secret','bad-key'));});
test('legacy plaintext is readable for controlled migration only',()=>{assert.equal(decrypt('old message',key),'old message');assert.equal(decrypt('',key),'');});
test('CSV quoting escapes quotes, commas and multiline text',()=>{assert.equal(csvCell('A,"B"'),'"A,""B"""');assert.equal(csvCell('A\nB'),'"A\nB"');});
test('CSV export prevents spreadsheet-formula injection',()=>{for(const s of ['=HYPERLINK("x")','+1','-1','@SUM(A1)','\t=1','  =1'])assert.ok(csvCell(s).startsWith('"\''));});
test('ID comparison supports populated and unpopulated document references',()=>{assert.equal(same({_id:'abc'},'abc'),true);assert.equal(same({_id:'abc'},{_id:'abc'}),true);assert.equal(same('abc','def'),false);});
