import mongoose from 'mongoose';

const classSchema = new mongoose.Schema({
  // One opaque room per lesson. The Daily room is provisioned only when its teacher starts it.
  roomId: {type:String, default:function(){return `quran-class-${this._id}`;}},
  startedAt: Date,
  startedBy: {type:mongoose.Schema.Types.ObjectId,ref:'User'},
  endedAt: Date,
  operationLock: {key:String,until:Date},
  liveRoom: {
    name:String, url:String, expiresAt:Date, readyAt:Date,
    closePending:{type:Boolean,default:false}, closedAt:Date,
  },
  teachingResource: {type:mongoose.Schema.Types.Mixed,default:()=>({kind:'quran',surah:1,ayah:1,translation:'en'})},
  resourceVersion:{type:Number,default:0},
  resourceUpdatedAt:Date,
  sharedNotes:{type:String,default:'',maxlength:12000},
  occurrenceKey:{type:String},
  teacherTimeZone:String,
  slotMinutes:Number,
  autoGenerated:{type:Boolean,default:false},
  enrollment: {type: mongoose.Schema.Types.ObjectId, ref: 'Enrollment'},
  ulma: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Ulma',
    required: true
  },
  student: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Student',
    required: true
  },
  course: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Course',
    required: true
  },
  date: {
    type: Date,
    required: true
  },
  utcStart: {
    type: Date,
    required: true
  },
  utcEnd: {
    type: Date,
    required: true
  },
  topic:{
    type: String,
    required: true
  },
  notes:{
    type: String,
      default: '',
      
  },
  status: {
    type: String,
    enum: ['scheduled', 'ongoing', 'completed', 'cancelled', 'paused'],
    default: 'scheduled'
  },
  attendance: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Attendance'
  },
  progress: {
    paraCompleted: Number,
    surahCompleted: String,
    remarks: String
  },
  recordingUrl: String,
  meetingLink: String,
  createdAt: {
    type: Date,
    default: Date.now
  }
});

classSchema.index({roomId:1},{unique:true,partialFilterExpression:{roomId:{$type:'string'}}});
classSchema.index({occurrenceKey:1},{unique:true,partialFilterExpression:{occurrenceKey:{$type:'string'}}});
classSchema.index({ulma:1,utcStart:1,utcEnd:1});
classSchema.index({student:1,utcStart:1,utcEnd:1});
export default mongoose.model('Class', classSchema);
